baseURL = "https://releaser.k3nny.fr/"
title = "releaser"
theme = "geekdoc"

pygmentsUseClasses = true
pygmentsCodeFences = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocLogo = "images/releaser-logo-1024.png"
  geekdocRepo = "https://git.k3nny.fr/k3nny/releaser"
  geekdocEditPath = "_edit/main/docs"
  geekdocSearch = true
  geekdocMenuBundle = true
  geekdocBreadcrumb = false
  geekdocToC = true

  [params.geekdocContentLicense]
    name = "Apache License 2.0"
    link = "https://git.k3nny.fr/k3nny/releaser/src/branch/main/LICENSE"
